name: Build Node binaries for macOS

on:
  workflow_dispatch:
  workflow_call:

jobs:
  macos-x64:
    runs-on: macos-11.0

    strategy:
      fail-fast: false
      matrix:
        target-node: [14, 16, 18, 19]

    steps:
      - uses: actions/checkout@v2

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - run: yarn install

      - run: yarn start --node-range node${{ matrix.target-node }} --output dist

      - name: Check if binary is compiled
        id: check_file
        run: |
          (test -f dist/*.sha256sum && echo ::set-output name=EXISTS::true) || echo ::set-output name=EXISTS::false

      - uses: actions/upload-artifact@v2
        if: steps.check_file.outputs.EXISTS == 'true'
        with:
          name: node${{ matrix.target-node }}-macos-x64
          path: dist/*
